---
book_repo: docs-book-csb-aws
layout_repo: pivotal-cf/docs-layout-repo
layout_repo_ref: 'master'
feedback_enabled: true

broken_link_exclusions: iefix|arrowhead
repo_link_enabled: true

public_host: docs.pivotal.io

elastic_search: true

sections:
  # cross-product resources
- repository:
    name: pivotal-cf/docs-partials
    ref: master
  directory: csb-aws/partials
  no_docs: true

- repository:
    name: pivotal-cf/docs-csb-aws
    ref: '1-0'
  directory: csb-aws/1-0
  subnav_template: csb_aws_subnav_1-0.erb
  product_info:
    use_local_header: true
    latest_stable_version: 1.0
    changelog_href: http://docs.pivotal.io/csb-aws/1-0/release-notes.html/
    local_header_img: /images/cloud_rings.png
    local_header_title: Tanzu Cloud Service Broker for AWS
    search_placeholder: Search CSB for AWS 1.0
    url_prefix: csb-aws/1-0
    local_product_version: 1.0
    local_header_links: []
    local_header_version_list: []
